os: linux
language: generic
sudo: required
services:
  - docker
script:
  - "cat /proc/cpuinfo"
  - "docker run -i -v \"${PWD}:/build-tensorflow\" daald/ubuntu32:xenial /bin/bash -c \"linux32 --32bit i386 /build-tensorflow/travis-ci/build-linux-x86.sh\""
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: artifacts/*
    skip_cleanup: true
    on:
      tags: true
